main_file: "main"

General:  
 Master_Volume:
  midi_cc: 7
  value: 70 
 Latch_Notes:
  midi_cc: 19
  value: 'Off'
  labels: [ 'Off', 'On' ]
 Seq_Select:
  midi_cc: 18
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14' ]
 Seq_Control:
  midi_cc: 114
  value: 'Stop'
  labels: [ 'Stop', 'Play', 'Record', 'Overdub', 'Undo' ]


Euclidian Controls:
 Density:
  midi_cc: 74
  value: '5/16'
  labels: [ '1/16', '2/16', '3/16', '4/16', '5/16', '6/16', '7/16', '8/16', '9/16', '10/16', '11/16', '12/16', '13/16', '14/16', '15/16', '16/16' ]
 Shift:
  midi_cc: 71
  value: '3'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16' ]
 Decay:
  midi_cc: 76
  value: 127
 Tempo:
  midi_cc: 77
  value: 40
