main_file: "main"

# New flag to explicitly request Organelle widget
use_organelle_widget: true


midi_controllers:

 Knob 1:
  midi_cc: 74
  value: 60
 Knob 2:
  midi_cc: 71
  value: 60
 Knob 3:
  midi_cc: 76
  value: 41
 Knob 4:
  midi_cc: 77
  value: 60
  
 Master_Volume:
  midi_cc: 7
  value: 28
 Menu:
  midi_cc: 114
  value: '1'
  labels: [ '1', '2', '3', '4', '5' ]
 Aux:
  midi_cc: 18
  value: '0'
  labels: [ '0', '1' ]
 Select:
  midi_cc: 19
  value: '0'
  labels: [ '0', '1' ]
 