main_file: "main"

# New flag to explicitly request EuclidSeq widget
use_euclidseq_widget: true


midi_controllers:

 Volume:
  midi_cc: 7
  value: 60

 Start/Stop: 
   midi_cc: 74
   value: 'Stop'
   labels: [ 'Stop', 'Start' ]

 Upper 3:
  midi_cc: 76
  value: 'Kit1'
  labels: [ 'Kit1', 'Kit2', 'MIDI Out' ]

 Lower 3:
  midi_cc: 77
  value: 'Tones'
  labels: [ 'Tones', 'Toms', 'MIDI Out' ]

  

 Channel:
  midi_cc: 114
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6']

 Note:
  midi_cc: 72
  value: 60

 Mode:
  midi_cc: 18
  value: 'Euclidean'
  labels: [ 'Polygon', 'Interval', 'Euclidean' ]

 Lengh:
  midi_cc: 19
  value: 4

 Hits:
  midi_cc: 16
  value: 4
 

 Offset:
  midi_cc: 17
  value: 0
  
 Interval:
  midi_cc: 91
  value: 4

 Mute:
  midi_cc: 79
  value: 0


 Tempo:
  midi_cc: 71
  value: 60
  
 