main_file: "main"

# New flag to explicitly request Organelle widget
use_organelle_widget: true


Master:
 Density: 
  midi_cc: 74
  value: 36
 Shift:
  midi_cc: 71
  value: 67
 Decay:
  midi_cc: 76
  value: 127
 Tempo:
  midi_cc: 77
  value: 35

General:  
 Master_Volume:
  midi_cc: 7
  value: 60 

