main_file: "main"

General:  
 Master_Volume:
  midi_cc: 7
  value: 60 
 Sequencer:
  midi_cc: 95
  value: 'Stop'
  labels: [ 'Stop', 'Play', 'Record' ]

Master:
 Transpose: 
  midi_cc: 91
  value: 63
 Pulse_Width:
  midi_cc: 79
  value: 63
 Filter_Amount:
  midi_cc: 72
  value: 30
 Sync Amount:
  midi_cc: 78
  value: 127

Amp_Envelope:
 Amp_Attack:
  midi_cc: 74
  value: 0
 Amp_Decay:
  midi_cc: 71
  value: 30
 Amp_Sustain:
  midi_cc: 76
  value: 70
 Amp_Release:
  midi_cc: 77
  value: 40


Width_Envelope:
 Width_Attack:
  midi_cc: 93
  value: 0
 Width_Decay:
  midi_cc: 73
  value: 0
 Width_Sustain:
  midi_cc: 75
  value: 60
 Width_Release:
  midi_cc: 114
  value: 40

Tone_Envelope:
 Tone_Attack:
  midi_cc: 18
  value: 0
 Tone_Decay:
  midi_cc: 19
  value: 0
 Tone_Sustain:
  midi_cc: 16
  value: 60
 Tone_Release:
  midi_cc: 17
  value: 40

