main_file: "main"

General:
 Master_Volume:
  midi_cc: 7
  value: 60 
 Seq_Select:
  midi_cc: 18
  value: '1'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14' ]
 Seq_Control:
  midi_cc: 114
  value: 'Stop'
  labels: [ 'Stop', 'Play', 'Record', 'Overdub', 'Undo' ]
 Record_Samples:
  midi_cc: 17
  value: 'Off'
  labels: [ 'Off', 'Record' ]
  
Tapey_Controls: 
 Input_Vol:
  midi_cc: 74
  value: 63 
 Tune:
  midi_cc: 71
  value: 68
 Ramp_Time:
  midi_cc: 76
  value: 0
 Warble:
  midi_cc: 77
  value: 0
  
Misc_Controls: 
 Latch_Notes:
  midi_cc: 19
  value: 'Off'
  labels: [ 'Off', 'On' ]
 Mode:
  midi_cc: 16
  value: 'Poly'
  labels: [ 'Mono', 'Poly' ]
 Sync:
  midi_cc: 91
  value: 'Off'
  labels: [ 'Off', 'On' ]
 Reverse:
  midi_cc: 79
  value: 'Off'
  labels: [ 'Off', 'On' ]