main_file: "main"

# New flag to explicitly request Organelle widget
use_organelle_widget: true


Master:
 Knob1: 
  midi_cc: 74
  value: 59
 Knob2:
  midi_cc: 71
  value: 30
 Knob3:
  midi_cc: 76
  value: 30
 Knob4:
  midi_cc: 77
  value: 51

General:  
 Master_Volume:
  midi_cc: 7
  value: 60

