main_file: "main"

Main:
 Volume_main:
  midi_cc: 7
  value: 100
 Expression_Pedal:
  midi_cc: 26
  value: 0
 Freeze Latch:
  midi_cc: 25
  value: 0
  labels: ["Off","On"]
 Freeze Momentary:
  midi_cc: 27
  value: 0
  labels: ["Off","On"]

Control:
 Grain_Size:
  midi_cc: 21
  value: 0
 Spread:
  midi_cc: 22
  value: 0
 Density:
  midi_cc: 23
  value: 0
 Wet_Dry:
  midi_cc: 24
  value: 0
