main_file: "main"

General:
 Master_Volume:
  midi_cc: 7
  value: 65
 Preset: 
  midi_cc: 74
  labels: [ 'Hammer Dulcimer', 'Multi Tapper', 'Wyleu Bells', 'Steel Horn', 'Copycat', 'Falling Chord', 'Xylo Beach', 'Ian Flute', 'User 1', 'User 2', 'User 3', 'User 4', 'User 5', 'User 6', 'User 7', 'User 8' ]
 Frequency:
  midi_cc: 71
  value: 60
 Model:
  midi_cc: 76
  value: 'String'
  labels: [ 'Dual', 'Waveshape', '2 Op FM', 'Formant', 'Harmonic', 'Wavetable', 'Chords', 'Speech', 'Grain', 'FilterNoise', 'Particle', 'String', 'Resonator', 'Kick', 'Snare', 'HiHat' ]

Tone Control:
 Harmonics:
  midi_cc: 77
  value: 0
 Timbre:
  midi_cc: 93
  value: 109  
 Morph:
  midi_cc: 73
  value: 53  
 Trigger Active:
  midi_cc: 75
  value: 'On'
  labels: [ 'Off', 'On' ]
  
Modulation:
 Mod Timbre:
  midi_cc: 114
  value: 60   
 Mod FM:
  midi_cc: 18
  value: 64    
 Mod Morph:
  midi_cc: 19
  value: 99
 Lowpass Gate:
  midi_cc: 16
  value: 0
   
Misc:
 Attack:
  midi_cc: 17
  value: 0
 Decay:
  midi_cc: 91
  value: 127 
 Save to Slot:
  midi_cc: 79
  labels: [ 'User 1', 'User 2', 'User 3', 'User 4', 'User 5', 'User 6', 'User 7', 'User 8' ]
 Save Preset:
  midi_cc: 72 
  value: 'No'
  labels: [ 'No', 'Yes' ]
  