main_file: "main.pd"
osc_zctrls: true

Main:
 volume:
  osc_path: "/zctrl/volume"
  value_min: 0
  value_max: 100
  value: 30
 frequency:
  osc_path: "/zctrl/frequency"
  value_min: 20
  value_max: 2000
  value: 440
 wave type:
  osc_path: "/zctrl/selectwave"
  labels: ["sin", "square", "saw"]
  ticks: [1, 2, 3]
  value_min: 1
  value_max: 3
  value: 1

   
