main_file: "main"

General:  
 Master_Volume:
  midi_cc: 7
  value: 63 
 Mix:
  midi_cc: 74
  value: 63
 Tempo:
  midi_cc: 71
  value: 63
 Resonance:
  midi_cc: 76
  value: 63

  
Misc_Controls: 
 Cutoff:
  midi_cc: 77
  value: 60
 Arp:
  midi_cc: 18
  value: 'Off'
  labels: [ 'Off', 'On' ]



