main_file: "main.pd"

midi_controllers:
 Start/stop:
  midi_cc: 18
  value: 'Stop'
  labels: [ 'Stop', 'Start', ]
 Volume:
  midi_cc: 7
  value: 30
 Tempo: 
  midi_cc: 71
  value: 50
 Rhythm:
  midi_cc: 73
  value: 'Rock 1A'
  labels: [ 'Rock 1A', 'Rock 1B', 'Rock 2A', 'Rock 2B', 'Rock 3A', 'Rock 3B', 'Rock 4A', 'Rock 4B', 'Disco 1A', 'Disco 1B', 'Disco 2A', 'Disco 2B', 'Foxtrott', 'Mambo', 'Cha-cha', 'Rumba', 'Beguine', 'Bossa Nova A', 'Bossa Nova B', 'Swing A', 'Swing B', ]
 
 Tamb/Guiro vol:
  midi_cc: 77
  value: 0
 Bass drum vol:
  midi_cc: 85
  value: 127
 Snare & percussion vol:
  midi_cc: 86
  value: 127
 Cymbals vol:
  midi_cc: 87
  value: 127

 Compressor:
  midi_cc: 76
  value: 'Off'
  labels: [ 'Off', 'On', ]

